import browser_cookie3
import download_bilibili as dl
import yt_dlp

# 直接从运行中的 Edge 读 cookies
print('Reading cookies from Edge...')
cj = browser_cookie3.edge(domain_name='.bilibili.com')
cookie_count = len(list(cj))
print(f'Got {cookie_count} bilibili cookies')

# 写到文件给 download_bilibili 用
with open('cookies.txt', 'w', encoding='utf-8') as f:
    f.write('# Netscape HTTP Cookie File\n')
    f.write('# Generated by browser_cookie3 from Edge\n\n')
    for cookie in cj:
        secure = 'TRUE' if cookie.secure else 'FALSE'
        expires = int(cookie.expires) if cookie.expires else 0
        domain = cookie.domain
        if domain and not domain.startswith('.'):
            domain = '.' + domain
        f.write(f'{domain}\tTRUE\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n')

print('Cookies saved, starting download...')
dl.download_bilibili_video('BV1wR4y1G7AN')
